// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jniqpfmzaimktkvgjgfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuaXFwZm16YWlta3RrdmdqZ2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzkyNzYsImV4cCI6MjA1NzkxNTI3Nn0.bXYtNJq85vYexN56b4BFGOSSKNZhvC-uQGGcn3SxH4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);